# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

get_subjectgroup_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)

load_spatial_features_group = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="load_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.results import (
    combine_map_layers as combine_map_layers,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    detect_geofence_crossings as detect_geofence_crossings,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polygon_layer as create_polygon_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "er_client_name": [],
        "time_range": [],
        "get_timezone": ["time_range"],
        "subject_obs": ["er_client_name", "time_range"],
        "subject_tracks": ["subject_obs"],
        "roi": [],
        "groupers": [],
        "crossings": ["subject_tracks", "roi"],
        "crossings_tz": ["crossings", "get_timezone"],
        "crossings_colormap": ["crossings_tz"],
        "temporal_index": ["crossings_colormap", "groupers"],
        "split_crossings": ["temporal_index", "groupers"],
        "base_map_defs": [],
        "crossings_map_display": ["split_crossings"],
        "roi_polygon_layer": ["roi"],
        "crossing_point_layer": ["crossings_map_display"],
        "combined_layers": ["roi_polygon_layer", "crossing_point_layer"],
        "ecomap": ["base_map_defs", "combined_layers"],
        "ecomap_html_url": ["ecomap"],
        "map_widget": ["ecomap_html_url"],
        "merged_map_widget": ["map_widget"],
        "crossings_table_display": ["split_crossings"],
        "crossings_table": ["crossings_table_display"],
        "crossings_table_html_url": ["crossings_table"],
        "table_widget": ["crossings_table_html_url"],
        "merged_table_widget": ["table_widget"],
        "dashboard": [
            "workflow_details",
            "merged_map_widget",
            "merged_table_widget",
            "groupers",
            "time_range",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "subject_obs": Node(
            async_task=get_subjectgroup_observations.validate()
            .set_task_instance_id("subject_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "raise_on_empty": False,
            }
            | (params_dict.get("subject_obs") or {}),
            method="call",
        ),
        "subject_tracks": Node(
            async_task=relocations_to_trajectory.validate()
            .set_task_instance_id("subject_tracks")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("subject_obs"),
            }
            | (params_dict.get("subject_tracks") or {}),
            method="call",
        ),
        "roi": Node(
            async_task=load_spatial_features_group.validate()
            .set_task_instance_id("roi")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("roi") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "crossings": Node(
            async_task=detect_geofence_crossings.validate()
            .set_task_instance_id("crossings")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "trajectory": DependsOn("subject_tracks"),
                "region_of_interest": DependsOn("roi"),
            }
            | (params_dict.get("crossings") or {}),
            method="call",
        ),
        "crossings_tz": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("crossings_tz")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("crossings"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "crossing_time",
                ],
            }
            | (params_dict.get("crossings_tz") or {}),
            method="call",
        ),
        "crossings_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("crossings_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("crossings_tz"),
                "input_column_name": "direction",
                "colormap": [
                    "#008000",
                    "#CC0000",
                ],
                "output_column_name": "direction_colormap",
            }
            | (params_dict.get("crossings_colormap") or {}),
            method="call",
        ),
        "temporal_index": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("temporal_index")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("crossings_colormap"),
                "time_col": "crossing_time",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("temporal_index") or {}),
            method="call",
        ),
        "split_crossings": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_crossings")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("temporal_index"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_crossings") or {}),
            method="call",
        ),
        "base_map_defs": Node(
            async_task=set_base_maps.validate()
            .set_task_instance_id("base_map_defs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "crossings_map_display": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("crossings_map_display")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "rename_columns": {
                    "crossing_time": "Crossing Time",
                    "direction": "Direction",
                    "extra__subject__name": "Subject",
                },
                "raise_if_not_found": False,
            }
            | (params_dict.get("crossings_map_display") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_crossings"),
            },
        ),
        "roi_polygon_layer": Node(
            async_task=create_polygon_layer.validate()
            .set_task_instance_id("roi_polygon_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("roi"),
                "layer_style": {
                    "filled": False,
                    "stroked": True,
                    "get_line_color": [
                        30,
                        30,
                        200,
                        200,
                    ],
                    "get_line_width": 2,
                },
                "legend": {
                    "title": "Region of Interest",
                    "values": [
                        {
                            "label": "Boundary",
                            "color": "rgba(30, 30, 200, 0.8)",
                        },
                    ],
                },
                "zoom": True,
            }
            | (params_dict.get("roi_polygon_layer") or {}),
            method="call",
        ),
        "crossing_point_layer": Node(
            async_task=create_point_layer.validate()
            .set_task_instance_id("crossing_point_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "fill_color_column": "direction_colormap",
                    "get_radius": 8,
                },
                "legend": {
                    "label_column": "Direction",
                    "color_column": "direction_colormap",
                },
                "tooltip_columns": [
                    "Crossing Time",
                    "Direction",
                    "Subject",
                ],
            }
            | (params_dict.get("crossing_point_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("crossings_map_display"),
            },
        ),
        "combined_layers": Node(
            async_task=combine_map_layers.validate()
            .set_task_instance_id("combined_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "static_layers": DependsOn("roi_polygon_layer"),
            }
            | (params_dict.get("combined_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["grouped_layers"],
                "argvalues": DependsOn("crossing_point_layer"),
            },
        ),
        "ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {
                    "placement": "top-left",
                },
                "legend_style": {
                    "title": "Crossings",
                    "placement": "bottom-right",
                },
                "static": False,
                "max_zoom": 20,
            }
            | (params_dict.get("ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers"],
                "argvalues": DependsOn("combined_layers"),
            },
        ),
        "ecomap_html_url": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("ecomap_html_url")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("ecomap_html_url") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("ecomap"),
            },
        ),
        "map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Geofence Crossings Map",
            }
            | (params_dict.get("map_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("ecomap_html_url"),
            },
        ),
        "merged_map_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("merged_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("map_widget"),
            }
            | (params_dict.get("merged_map_widget") or {}),
            method="call",
        ),
        "crossings_table_display": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("crossings_table_display")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "rename_columns": {
                    "crossing_time": "Crossing Time",
                    "direction": "Direction",
                    "extra__subject__name": "Subject",
                    "longitude": "Longitude",
                    "latitude": "Latitude",
                },
                "raise_if_not_found": False,
            }
            | (params_dict.get("crossings_table_display") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_crossings"),
            },
        ),
        "crossings_table": Node(
            async_task=draw_table.validate()
            .set_task_instance_id("crossings_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "columns": [
                    "Crossing Time",
                    "Direction",
                    "Subject",
                    "Longitude",
                    "Latitude",
                ],
            }
            | (params_dict.get("crossings_table") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("crossings_table_display"),
            },
        ),
        "crossings_table_html_url": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("crossings_table_html_url")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("crossings_table_html_url") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("crossings_table"),
            },
        ),
        "table_widget": Node(
            async_task=create_table_widget_single_view.validate()
            .set_task_instance_id("table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Geofence Crossings Table",
            }
            | (params_dict.get("table_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("crossings_table_html_url"),
            },
        ),
        "merged_table_widget": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("merged_table_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("table_widget"),
            }
            | (params_dict.get("merged_table_widget") or {}),
            method="call",
        ),
        "dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("merged_map_widget"),
                    DependsOn("merged_table_widget"),
                ],
                "groupers": DependsOn("groupers"),
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
