# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.results import (
    combine_map_layers as combine_map_layers,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    detect_geofence_crossings as detect_geofence_crossings,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    load_spatial_features_group as load_spatial_features_group,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polygon_layer as create_polygon_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_table as draw_table
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    get_timezone = (
        get_timezone_from_time_range.validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params_dict.get("get_timezone") or {}))
        .call()
    )

    subject_obs = (
        get_subjectgroup_observations.validate()
        .set_task_instance_id("subject_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            raise_on_empty=False,
            **(params_dict.get("subject_obs") or {}),
        )
        .call()
    )

    subject_tracks = (
        relocations_to_trajectory.validate()
        .set_task_instance_id("subject_tracks")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=subject_obs, **(params_dict.get("subject_tracks") or {}))
        .call()
    )

    roi = (
        load_spatial_features_group.validate()
        .set_task_instance_id("roi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("roi") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    crossings = (
        detect_geofence_crossings.validate()
        .set_task_instance_id("crossings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trajectory=subject_tracks,
            region_of_interest=roi,
            **(params_dict.get("crossings") or {}),
        )
        .call()
    )

    crossings_tz = (
        convert_values_to_timezone.validate()
        .set_task_instance_id("crossings_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=crossings,
            timezone=get_timezone,
            columns=["crossing_time"],
            **(params_dict.get("crossings_tz") or {}),
        )
        .call()
    )

    crossings_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("crossings_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=crossings_tz,
            input_column_name="direction",
            colormap=["#008000", "#CC0000"],
            output_column_name="direction_colormap",
            **(params_dict.get("crossings_colormap") or {}),
        )
        .call()
    )

    temporal_index = (
        add_temporal_index.validate()
        .set_task_instance_id("temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=crossings_colormap,
            time_col="crossing_time",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("temporal_index") or {}),
        )
        .call()
    )

    split_crossings = (
        split_groups.validate()
        .set_task_instance_id("split_crossings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=temporal_index,
            groupers=groupers,
            **(params_dict.get("split_crossings") or {}),
        )
        .call()
    )

    base_map_defs = (
        set_base_maps.validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("base_map_defs") or {}))
        .call()
    )

    crossings_map_display = (
        map_columns.validate()
        .set_task_instance_id("crossings_map_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "crossing_time": "Crossing Time",
                "direction": "Direction",
                "extra__subject__name": "Subject",
            },
            raise_if_not_found=False,
            **(params_dict.get("crossings_map_display") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_crossings)
    )

    roi_polygon_layer = (
        create_polygon_layer.validate()
        .set_task_instance_id("roi_polygon_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=roi,
            layer_style={
                "filled": False,
                "stroked": True,
                "get_line_color": [30, 30, 200, 200],
                "get_line_width": 2,
            },
            legend={
                "title": "Region of Interest",
                "values": [{"label": "Boundary", "color": "rgba(30, 30, 200, 0.8)"}],
            },
            zoom=True,
            **(params_dict.get("roi_polygon_layer") or {}),
        )
        .call()
    )

    crossing_point_layer = (
        create_point_layer.validate()
        .set_task_instance_id("crossing_point_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"fill_color_column": "direction_colormap", "get_radius": 8},
            legend={"label_column": "Direction", "color_column": "direction_colormap"},
            tooltip_columns=["Crossing Time", "Direction", "Subject"],
            **(params_dict.get("crossing_point_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=crossings_map_display)
    )

    combined_layers = (
        combine_map_layers.validate()
        .set_task_instance_id("combined_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=roi_polygon_layer,
            **(params_dict.get("combined_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=crossing_point_layer)
    )

    ecomap = (
        draw_ecomap.validate()
        .set_task_instance_id("ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={"title": "Crossings", "placement": "bottom-right"},
            static=False,
            max_zoom=20,
            **(params_dict.get("ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=combined_layers)
    )

    ecomap_html_url = (
        persist_text.validate()
        .set_task_instance_id("ecomap_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("ecomap_html_url") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ecomap)
    )

    map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Geofence Crossings Map", **(params_dict.get("map_widget") or {})
        )
        .map(argnames=["view", "data"], argvalues=ecomap_html_url)
    )

    merged_map_widget = (
        merge_widget_views.validate()
        .set_task_instance_id("merged_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=map_widget, **(params_dict.get("merged_map_widget") or {}))
        .call()
    )

    crossings_table_display = (
        map_columns.validate()
        .set_task_instance_id("crossings_table_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "crossing_time": "Crossing Time",
                "direction": "Direction",
                "extra__subject__name": "Subject",
                "longitude": "Longitude",
                "latitude": "Latitude",
            },
            raise_if_not_found=False,
            **(params_dict.get("crossings_table_display") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_crossings)
    )

    crossings_table = (
        draw_table.validate()
        .set_task_instance_id("crossings_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=["Crossing Time", "Direction", "Subject", "Longitude", "Latitude"],
            **(params_dict.get("crossings_table") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=crossings_table_display)
    )

    crossings_table_html_url = (
        persist_text.validate()
        .set_task_instance_id("crossings_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("crossings_table_html_url") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=crossings_table)
    )

    table_widget = (
        create_table_widget_single_view.validate()
        .set_task_instance_id("table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Geofence Crossings Table", **(params_dict.get("table_widget") or {})
        )
        .map(argnames=["view", "data"], argvalues=crossings_table_html_url)
    )

    merged_table_widget = (
        merge_widget_views.validate()
        .set_task_instance_id("merged_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=table_widget, **(params_dict.get("merged_table_widget") or {}))
        .call()
    )

    dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[merged_map_widget, merged_table_widget],
            groupers=groupers,
            time_range=time_range,
            **(params_dict.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
