# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_subjectgroup_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)

load_spatial_features_group = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="load_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import create_polygon_layer as create_polygon_layer
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from geofence_crossing_tasks import combine_map_layers as combine_map_layers
from geofence_crossing_tasks import (
    detect_geofence_crossings as detect_geofence_crossings,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    subject_obs = (
        task(get_subjectgroup_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("subject_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            raise_on_empty=False,
            **(params.get("subject_obs") or {}),
        )
        .call()
    )

    subject_tracks = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("subject_tracks")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=subject_obs, **(params.get("subject_tracks") or {}))
        .call()
    )

    roi = (
        task(load_spatial_features_group)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("roi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("roi") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=[{"index_name": "extra__subject__name"}],
            **(params.get("groupers") or {}),
        )
        .call()
    )

    crossings = (
        task(detect_geofence_crossings)
        .validate()
        .set_task_instance_id("crossings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            trajectory=subject_tracks,
            region_of_interest=roi,
            **(params.get("crossings") or {}),
        )
        .call()
    )

    crossings_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("crossings_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=crossings,
            timezone=get_timezone,
            columns=["crossing_time"],
            **(params.get("crossings_tz") or {}),
        )
        .call()
    )

    crossings_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("crossings_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=crossings_tz,
            input_column_name="direction",
            colormap=["#008000", "#CC0000"],
            output_column_name="direction_colormap",
            **(params.get("crossings_colormap") or {}),
        )
        .call()
    )

    temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=crossings_colormap,
            time_col="crossing_time",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("temporal_index") or {}),
        )
        .call()
    )

    split_crossings = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_crossings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=temporal_index,
            groupers=groupers,
            **(params.get("split_crossings") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    crossings_map_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("crossings_map_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "crossing_time": "Crossing Time",
                "direction": "Direction",
                "extra__subject__name": "Subject",
            },
            raise_if_not_found=False,
            **(params.get("crossings_map_display") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_crossings)
    )

    roi_polygon_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("roi_polygon_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=roi,
            layer_style={
                "filled": False,
                "stroked": True,
                "get_line_color": [30, 30, 200, 200],
                "get_line_width": 2,
            },
            legend={
                "title": "Region of Interest",
                "values": [{"label": "Boundary", "color": "rgba(30, 30, 200, 0.8)"}],
            },
            zoom=True,
            **(params.get("roi_polygon_layer") or {}),
        )
        .call()
    )

    crossing_point_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("crossing_point_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"fill_color_column": "direction_colormap", "get_radius": 8},
            legend={"label_column": "Direction", "color_column": "direction_colormap"},
            tooltip_columns=["Crossing Time", "Direction", "Subject"],
            **(params.get("crossing_point_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=crossings_map_display)
    )

    combined_layers = (
        task(combine_map_layers)
        .validate()
        .set_task_instance_id("combined_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=roi_polygon_layer, **(params.get("combined_layers") or {})
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=crossing_point_layer)
    )

    ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={"title": "Crossings", "placement": "bottom-right"},
            static=False,
            max_zoom=20,
            **(params.get("ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=combined_layers)
    )

    ecomap_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("ecomap_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("ecomap_html_url") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ecomap)
    )

    map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Geofence Crossings Map", **(params.get("map_widget") or {}))
        .map(argnames=["view", "data"], argvalues=ecomap_html_url)
    )

    merged_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=map_widget, **(params.get("merged_map_widget") or {}))
        .call()
    )

    crossings_table_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("crossings_table_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "crossing_time": "Crossing Time",
                "direction": "Direction",
                "extra__subject__name": "Subject",
                "longitude": "Longitude",
                "latitude": "Latitude",
            },
            raise_if_not_found=False,
            **(params.get("crossings_table_display") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_crossings)
    )

    crossings_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("crossings_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=["Crossing Time", "Direction", "Subject", "Longitude", "Latitude"],
            **(params.get("crossings_table") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=crossings_table_display)
    )

    crossings_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("crossings_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("crossings_table_html_url") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=crossings_table)
    )

    table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Geofence Crossings Table", **(params.get("table_widget") or {}))
        .map(argnames=["view", "data"], argvalues=crossings_table_html_url)
    )

    merged_table_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("merged_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=table_widget, **(params.get("merged_table_widget") or {}))
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[merged_map_widget, merged_table_widget],
            groupers=groupers,
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
